name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - '.gitignore'
      - '.github/dependabot.yml'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '.gitignore'
      - '.github/dependabot.yml'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn --batch-mode compile
